{% set name = "python-stdnum" %}
{% set version = "1.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad2a2cf2eb025de408210235f36b4ae31252de3186240ccaa8126e117cb82690

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6


test:
  imports:
    - stdnum

about:
  home: https://pypi.org/project/python-stdnum/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A Python module to parse, validate and reformat standard numbers and codes in different formats.

  description: |
    A Python module to parse, validate and reformat standard numbers and codes in different formats. It contains a large collection of number formats.
    Basically any number or code that has some validation mechanism available or some common formatting is eligible for inclusion in this library.

  doc_url: https://arthurdejong.org/python-stdnum/
  dev_url: https://arthurdejong.org/python-stdnum/

extra:
  recipe-maintainers:
    - kcemenike
